let count1=10;
setTimeout(()=>{
       document.querySelector(".count").innerHTML=count1;
       setTimeout(()=>{
        document.querySelector(".count").innerHTML=--count1;
        setTimeout(()=>{
            document.querySelector(".count").innerHTML=--count1;
            setTimeout(()=>{
                document.querySelector(".count").innerHTML=--count1;
                setTimeout(()=>{
                    document.querySelector(".count").innerHTML=--count1;
                    setTimeout(()=>{
                        document.querySelector(".count").innerHTML=--count1;
                        setTimeout(()=>{
                            document.querySelector(".count").innerHTML=--count1;
                            setTimeout(()=>{
                                document.querySelector(".count").innerHTML=--count1;
                                setTimeout(()=>{
                                    document.querySelector(".count").innerHTML=--count1;
                                    setTimeout(()=>{
                                        document.querySelector(".count").innerHTML=--count1;
                                        setTimeout(()=>{
                                            document.querySelector(".count").innerHTML=--count1;  
                                         setTimeout(()=>{
                                            document.querySelector(".count").innerHTML="Happy Independence Day...!";
                                             },1000)
                                         },1000)
                                     },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)
